In [1]:
import numpy as np
import pyvista as pv
import os
import run_output_bonds_func as robf
import get_coordinate as gc
import importlib
import matplotlib.pyplot as plt
importlib.reload(robf)
importlib.reload(gc)

In [2]:
def make_position_data_ndarray(connection_data):
    position_data = gc.get_coordinate_data(connection_data)
    return position_data.values

In [3]:
def plot_coordinate_vista(connection_data, target, output_dir = "output_oxDNA"):
    point_cloud = make_position_data_ndarray(connection_data)
    #print(point_cloud)
    pdata = pv.PolyData(point_cloud)
    #display(pdata)#N pointsの値, int
    n_points = pdata.n_points
    #pdata['orig_sphere'] = np.arange(n_points)
    sphere = pv.Sphere(radius=0.2, phi_resolution=10, theta_resolution=10)
    #display(sphere)
    # create many spheres from the point cloud
    pc = pdata.glyph(scale=False, geom=sphere)
    #display(pc)
    pc.plot(cmap='Reds')
    
    plt.savefig(os.path.join(output_dir, "{}.png".format(target)))

In [6]:
def main():
    target = "e0"
    connection_data = robf.create_connection_data(target, output_dir = "output_oxDNA")
    plot_coordinate_vista(connection_data, target)

In [7]:
if __name__ == "__main__":
    main()

,id1,id2,HB,strand,nucleotide,position_rx,position_ry,position_rz,id2_strand
0,0,1,0.000000,1,T,-227.626991,70.706160,19.573057,1
1,0,20,0.000000,1,T,-227.626991,70.706160,19.573057,1
2,0,22,-0.000000,1,T,-227.626991,70.706160,19.573057,1
3,1,2,0.000000,1,T,-227.306824,71.054906,19.266832,1
4,1,19,0.000000,1,T,-227.306824,71.054906,19.266832,1
5,1,21,-0.000000,1,T,-227.306824,71.054906,19.266832,1
6,2,3,0.000000,1,A,-227.152888,71.566034,18.970770,1
7,2,18,0.000000,1,A,-227.152888,71.566034,18.970770,1
8,2,19,-0.626961,1,A,-227.152888,71.566034,18.970770,1
9,2,20,0.000000,1,A,-227.152888,71.566034,18.970770,1
10,3,4,0.000000,1,T,-227.348633,72.056276,18.743501,1
11,3,17,-0.000000,1,T,-227.348633,72.056276,18.743501,1
12,3,19,0.000000,1,T,-227.348633,72.056276,18.743501,1
13,4,5,0.000000,1,T,-227.618164,72.552116,18.612688,1
14,4,16,-0.000000,1,T,-227.618164,72.552116,18.612688,1
15,4,17,-0.683989,1,T,-227.618164,72.552116,18.612688,1
16,4,18,0.000000,1,T,-227.618164,72.552116,18.612688,1
17,5,6,0.000000,1,C,-227.952099,72.931056,18.758104,1
18,5,15,0.000000,1,C,-227.952099,72.931056,18.758104,1
19,5,17,0.000000,1,C,-227.952099,72.931056,18.758104,1
20,6,7,0.000000,1,T,-227.974058,73.506158,18.889259,1
21,6,14,0.000000,1,T,-227.974058,73.506158,18.889259,1
22,6,15,-0.422575,1,T,-227.974058,73.506158,18.889259,1
23,6,16,0.000000,1,T,-227.974058,73.506158,18.889259,1
24,7,8,0.000000,1,C,-228.059472,73.874731,19.210856,1
25,7,13,0.000000,1,C,-228.059472,73.874731,19.210856,1
26,7,15,0.000000,1,C,-228.059472,73.874731,19.210856,1
27,8,9,0.000000,1,T,-227.936270,74.240156,19.564273,1
28,8,12,0.000000,1,T,-227.936270,74.240156,19.564273,1
29,8,14,-0.000000,1,T,-227.936270,74.240156,19.564273,1
30,9,10,0.000000,1,T,-227.709984,74.730054,19.804178,1
31,9,11,0.000000,1,T,-227.709984,74.730054,19.804178,1
32,9,12,-0.219726,1,T,-227.709984,74.730054,19.804178,1
33,9,13,-0.000000,1,T,-227.709984,74.730054,19.804178,1
34,10,11,0.000000,1,G,-227.519515,75.183897,19.303022,1
35,11,12,0.000000,1,C,-227.486054,74.860131,18.846590,1
36,12,13,0.000000,1,T,-227.234008,74.476688,18.691399,1
37,13,14,0.000000,1,A,-226.969966,74.008217,18.856612,1
38,14,15,0.000000,1,A,-226.899627,73.642592,19.175419,1
39,15,16,0.000000,1,T,-227.042655,73.230978,19.512338,1
40,16,17,0.000000,1,A,-227.254733,72.846946,19.679069,1
41,17,18,0.000000,1,A,-227.620628,72.450434,19.785496,1
42,18,19,0.000000,1,G,-228.024335,72.024142,19.702798,1
43,19,20,0.000000,1,A,-228.318194,71.686591,19.345734,1
44,20,21,0.000000,1,G,-228.473262,71.173917,18.979819,1
45,21,22,0.000000,1,A,-228.268722,70.854661,18.613739,1
46,22,23,0.000000,1,A,-228.101115,70.385714,18.581376,1
47,23,24,0.000000,1,C,-227.728476,70.043313,18.680638,1
48,24,25,0.000000,1,G,-227.593136,69.604352,18.797700,1

ValueError: Points array must contain three values per point. Shape is (49, 4) and should be (X, 3)